version: "3.8"

services:

  mongo-db:
    image: mongo:4.0.11
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
  chat-app:
    build: .
    container_name: online_chat
    restart: always
    ports:
      - "7777:7777"
    links:
      - mongo-db
    depends_on:
      - mongo-db
      - mongo-express
volumes:
  mongo: {}

